name: Test and Upload Python Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    strategy:
      matrix:
        pythonvers: ['3.9','3.10']
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies and run test
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Setup ${{ matrix.pythonvers }}
      uses: actions/setup-python@v1
      with:
          python-version: ${{ matrix.pythonvers }}
    - name: Start testing with pytest on Python ${{ matrix.pythonvers }}
      run:
        pytest  